"""Node-side implementation for setup-cluster.py; sent over management SSH.

Only public inventory and public SSH keys leave the node. Backups, including
any credentials in existing Netplan files, stay in a root-only local journal.
"""

import base64
import fnmatch
import grp
import hashlib
import ipaddress
import json
import os
from pathlib import Path
import pwd
import re
import shlex
import shutil
import stat
import struct
import subprocess
import tempfile

NETPLAN = Path("/etc/netplan/98-spark-vllm-docker.yaml")
STATE = Path("/var/lib/spark-vllm/setup-cluster")
DEFAULT_MTU = 9000
PORTS = {p: [f"enp1s0f{p}np{p}", f"enP2p1s0f{p}np{p}"] for p in (0, 1)}
ENV_KEYS = {"CLUSTER_NODES", "COPY_HOSTS", "LOCAL_IP", "ETH_IF", "IB_IF", "CLUSTER_LINKS",
            "CONTAINER_NCCL_NET_PLUGIN", "CONTAINER_NCCL_IB_SUBNET_AWARE_ROUTING",
            "CONTAINER_NCCL_IB_MERGE_NICS", "CONTAINER_NCCL_ALGO"}
ENV_HEADER = b"# Cluster configuration generated by setup-cluster.sh\n"


def mtu_value(value):
    if isinstance(value, str) and re.fullmatch(r"[0-9]+", value):
        value = int(value)
    if type(value) is not int or not 68 <= value <= 65535:
        raise ValueError("MTU must be an integer between 68 and 65535 bytes")
    return value


def requested_mtu(request):
    # Journals from before --mtu always configured 9000.
    return mtu_value(request.get("mtu", DEFAULT_MTU))


def netplan_path(value):
    """Validate a destination, without resolving a path on the head's filesystem."""
    path = Path(value)
    if path.parent != NETPLAN.parent or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*\.yaml", path.name):
        raise ValueError(f"--netplan-file must be an absolute .yaml path directly inside {NETPLAN.parent}")
    return path


def requested_netplan(request):
    return netplan_path(request.get("netplan_file", str(NETPLAN)))


def netplan_directories():
    # /lib is normally a compatibility symlink to /usr/lib on Ubuntu.
    return Path("/lib/netplan").resolve(), NETPLAN.parent, Path("/run/netplan")


def run(argv, *, user=None, check=True, binary=False, input=None, stdin=None, timeout=150):
    command = argv
    if user:
        argv = ["runuser", "-u", user, "--", *argv]
    result = subprocess.run(argv, capture_output=True, text=not binary, input=input, stdin=stdin, timeout=timeout)
    if check and result.returncode:
        # Only ip diagnostics are safe here; Netplan output can contain secrets.
        if command[0] == "ip":
            detail = result.stderr.decode(errors="replace") if binary else result.stderr
            raise ValueError(f"{shlex.join(command)} failed (exit {result.returncode}): {detail.strip()}")
        raise ValueError(f"{Path(argv[0]).name} failed (exit {result.returncode})")
    return result


def no_symlinks(path):
    for part in [path, *path.parents]:
        if part.is_symlink():
            raise ValueError(f"Refusing symlink: {part}")


def snapshot(path):
    no_symlinks(path)
    if not path.exists():
        return None
    info = path.stat()
    if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
        raise ValueError(f"Expected a regular file with one link: {path}")
    return {"data": base64.b64encode(path.read_bytes()).decode(),
            "mode": stat.S_IMODE(info.st_mode), "uid": info.st_uid, "gid": info.st_gid}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def atomic_write(path, data, mode=0o600, uid=0, gid=0):
    no_symlinks(path)
    fd, name = tempfile.mkstemp(prefix=".spark-vllm-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            os.fchown(stream.fileno(), uid, gid)
            os.fchmod(stream.fileno(), mode)
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(name, path)
        directory = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        if os.path.exists(name):
            os.unlink(name)


class Journal:
    def __init__(self, state):
        self.state = state

    def save(self):
        atomic_write(STATE / "journal.json", json.dumps(self.state).encode())

    def write(self, path, data, mode=0o600, uid=0, gid=0):
        if any(entry["path"] == str(path) for entry in self.state["files"]):
            raise ValueError(f"Already changed in this transaction: {path}")
        self.state["files"].append({"path": str(path), "before": snapshot(path),
                                    "after": digest(data), "mode": mode,
                                    "uid": uid, "gid": gid,
                                    "after_data": base64.b64encode(data).decode()})
        self.save()  # Write-ahead journal, including operations interrupted mid-write.
        atomic_write(path, data, mode, uid, gid)

    def directory(self, path, uid, gid):
        no_symlinks(path)
        if path.exists():
            info = path.stat()
            if not path.is_dir() or info.st_uid != uid or info.st_mode & 0o022:
                raise ValueError(f"Directory must be owned by the login user and not group/world writable: {path}")
            return
        self.state["directories"].append(str(path))
        self.save()
        path.mkdir(mode=0o700)
        os.chown(path, uid, gid)


def merge_env(original, values):
    """Replace cluster fields without evaluating or disclosing unrelated values."""
    if not set(values) <= ENV_KEYS:
        raise ValueError("Unexpected generated .env setting")
    kept = []
    for number, line in enumerate(original.splitlines(keepends=True), 1):
        stripped = line.strip()
        if stripped == ENV_HEADER.strip():
            continue
        if stripped and not stripped.startswith(b"#"):
            key, separator, value = stripped.partition(b"=")
            if not separator or not re.fullmatch(rb"[A-Za-z_][A-Za-z0-9_]*", key.strip()):
                raise ValueError(f"Existing .env must use single-line KEY=value entries (line {number})")
            value = value.strip()
            if value[:1] in (b"'", b'"') and (len(value) < 2 or value[-1:] != value[:1]):
                raise ValueError(f"Existing .env has an unsupported quoted value (line {number})")
            if key.strip().decode("ascii") in ENV_KEYS:
                continue
        kept.append(line)
    result = b"".join(kept)
    if result and not result.endswith(b"\n"):
        result += b"\n"
    result += ENV_HEADER
    for key, value in values.items():
        # Compatible with both repository dotenv readers (neither executes a
        # shell). Only JSON is quoted; generated scalars use a restricted set.
        if key == "CLUSTER_LINKS":
            value = json.dumps(json.loads(value), separators=(",", ":"))
            if "'" in value or "\n" in value:
                raise ValueError("Invalid generated CLUSTER_LINKS")
            value = "'" + value + "'"
        elif not re.fullmatch(r"[A-Za-z0-9_.,:-]+", value):
            raise ValueError(f"Invalid generated {key}")
        result += f"{key}={value}\n".encode()
    return result


def env_contents(request, account):
    path = Path(request["env_file"])
    if not path.is_absolute() or ".." in path.parts:
        raise ValueError("Head .env path must be absolute without parent traversal")
    no_symlinks(path)
    parent = path.parent.stat()
    if not path.parent.is_dir() or parent.st_uid != account.pw_uid:
        raise ValueError("Head .env directory must exist and be owned by the user")
    before = snapshot(path)
    if before and before["uid"] != account.pw_uid:
        raise ValueError("Head .env must be owned by the user")
    contents = merge_env(base64.b64decode(before["data"]) if before else b"", request["env_values"])
    return path, before, contents


def env_fingerprint(before):
    return digest(json.dumps(before, sort_keys=True).encode())


def install_env(request, account, journal):
    path, before, contents = env_contents(request, account)
    if env_fingerprint(before) != request["env_before"]:
        raise ValueError(f"Head configuration changed during setup: {path}; preserve/reconcile edits before retrying")
    if any(entry["path"] == str(path) for entry in journal.state["files"]):
        check_restore(journal)
        if before and base64.b64decode(before["data"]) == contents:
            return {}  # Repeated --save-env preserves the original before-image.
        raise ValueError(f"Configuration was already saved by this setup: {path}; restore before replacing it")
    # Before-image and contents stay in the head's existing root-only journal.
    journal.write(path, contents, uid=account.pw_uid, gid=before["gid"] if before else account.pw_gid)
    return {}


def docker_membership(account):
    try:
        group = grp.getgrnam("docker")
    except KeyError:
        return {"exists": False, "gid": None, "member": False}
    return {"exists": True, "gid": group.gr_gid,
            "member": group.gr_gid in os.getgrouplist(account.pw_name, account.pw_gid)}


def docker_preflight(account):
    membership = docker_membership(account)
    if not membership["member"]:
        commands = ["usermod", "gpasswd"] + ([] if membership["exists"] else ["groupadd", "groupdel"])
        for command in commands:
            if not shutil.which(command):
                raise ValueError(f"Docker group setup requires {command}")
    return membership


def check_docker_restore(journal):
    recorded = journal.state.get("docker")
    if not recorded:
        return
    account = pwd.getpwnam(journal.state["user"])
    current = docker_membership(account)
    if current["exists"] and recorded.get("gid") != current["gid"]:
        raise ValueError("Docker group identity changed; reconcile membership before restore/repair")


def ensure_docker(account, journal):
    current = docker_preflight(account)
    if "docker" not in journal.state:
        journal.state["docker"] = {"before_member": current["member"], "gid": current["gid"],
                                   "created": not current["exists"]}
        journal.save()  # Record intent before group creation or membership changes.
    recorded = journal.state["docker"]
    if current["exists"] and recorded["gid"] is not None and current["gid"] != recorded["gid"]:
        raise ValueError("Docker group identity changed; refusing to modify a replacement group")
    if not current["exists"]:
        if recorded["gid"] is not None:
            raise ValueError("The recorded docker group was removed; reconcile it before repair")
        run(["groupadd", "--system", "docker"])
        current = docker_membership(account)
        recorded["gid"] = current["gid"]
        journal.save()
    elif recorded["gid"] is None:
        # A kill between groupadd and saving its GID cannot prove group ownership.
        # Adopt it for membership repair, but never delete it during restoration.
        recorded.update(gid=current["gid"], created=False)
        journal.save()
    added = not current["member"]
    if added:
        run(["usermod", "-a", "-G", "docker", account.pw_name])
    if not docker_membership(account)["member"]:
        raise ValueError("Docker group membership did not take effect in the account database")
    return {"added": added}


def restore_docker(journal):
    recorded = journal.state.get("docker")
    if not recorded:
        return
    check_docker_restore(journal)
    account = pwd.getpwnam(journal.state["user"])
    current = docker_membership(account)
    if not current["exists"]:
        return
    if not recorded["before_member"] and current["member"]:
        run(["gpasswd", "-d", account.pw_name, "docker"])
    if recorded["created"]:
        group = grp.getgrnam("docker")
        if not group.gr_mem and not any(user.pw_gid == group.gr_gid for user in pwd.getpwall()):
            run(["groupdel", "docker"])
        # Retain a helper-created group if other users have since adopted it.


def docker_access(account):
    if not shutil.which("docker"):
        return "Docker CLI is not installed"
    # Fresh supplementary groups; no containers are launched or changed. Keep
    # daemon/environment diagnostics private and bypass inherited remote contexts.
    result = run(["docker", "--host", "unix:///var/run/docker.sock", "info", "--format", "{{.ServerVersion}}"],
                 user=account.pw_name, check=False, timeout=30)
    return None if result.returncode == 0 else "Docker daemon/socket is unavailable to a fresh user session"


def lldp_neighbors():
    """Optional, read-only physical discovery. Keep only CX7 port MACs."""
    if not shutil.which("lldpctl"):
        return {}
    try:
        result = run(["lldpctl", "-f", "json"], check=False)
        if result.returncode:
            return {}
        entries = json.loads(result.stdout).get("lldp", {}).get("interface", [])
        if isinstance(entries, dict):
            entries = [entries]
        neighbors = {}
        for entry in entries:
            for name, peer in entry.items():
                if name not in PORTS[0] + PORTS[1]:
                    continue
                port = peer.get("port", {}).get("id", {})
                # Unknown port identities must make this observation ambiguous.
                mac = str(port.get("value", "")).lower() if port.get("type") == "mac" else "unknown"
                neighbors.setdefault(name, []).append(mac)
        return neighbors
    except (OSError, ValueError, TypeError, AttributeError, subprocess.SubprocessError):
        return {}


def inventory(user):
    for tool in ("ip", "netplan", "ssh", "ssh-keygen", "ping", "runuser"):
        if not shutil.which(tool):
            raise ValueError(f"Required command is missing: {tool}")
    import yaml  # Supplied by Ubuntu's Netplan packages; never install dependencies.
    account = pwd.getpwnam(user)
    links = json.loads(run(["ip", "-j", "address", "show"]).stdout)
    for item in links:
        driver = Path("/sys/class/net") / item["ifname"] / "device/driver"
        if driver.exists():
            item["driver"] = driver.resolve().name
    by_name = {item["ifname"]: item for item in links}
    ports = []
    for port, names in PORTS.items():
        if all(name in by_name and "LOWER_UP" in by_name[name]["flags"] for name in names):
            ports.append(port)
    host_keys = []
    for key in Path("/etc/ssh").glob("ssh_host_*_key.pub"):
        fields = key.read_text().split()
        if len(fields) >= 2:
            host_keys.append(" ".join(fields[:2]))
    if not host_keys:
        raise ValueError("No SSH host public keys found in /etc/ssh")
    return {"ports": ports, "links": links, "host_keys": host_keys, "lldp": lldp_neighbors(),
            "home": account.pw_dir, "uid": account.pw_uid,
            "routes": json.loads(run(["ip", "-j", "-4", "route", "show", "table", "all"]).stdout)}


def matches_cx7(match, interfaces, links):
    for name in interfaces:
        link = links.get(name, {})
        if not fnmatch.fnmatchcase(name, match.get("name", "*")):
            continue
        if "macaddress" in match and link.get("address") and match["macaddress"].lower() != link["address"].lower():
            continue
        drivers = match.get("driver", ["*"])
        if isinstance(drivers, str):
            drivers = [drivers]
        if link.get("driver") and not any(fnmatch.fnmatchcase(link["driver"], driver) for driver in drivers):
            continue
        return True
    return False


def netplan_changes(interfaces, links=(), target=None):
    """Move exact Ethernet definitions; refuse ambiguous matches and dependencies."""
    import yaml
    target = netplan_path(target if target is not None else NETPLAN)
    changes = {}
    by_name = {item["ifname"]: item for item in links}
    for directory in netplan_directories():
        for path in sorted(directory.glob("*.yaml")):
            # Read locally only. Never send the parsed document to the head node.
            before = snapshot(path)
            try:
                document = yaml.safe_load(base64.b64decode(before["data"])) or {}
                network = document.get("network", {})
                ethernets = network.get("ethernets", {})
                for kind in ("bonds", "bridges", "vlans"):
                    for definition in network.get(kind, {}).values():
                        if set(definition.get("interfaces", [])) & set(interfaces) or definition.get("link") in interfaces:
                            raise ValueError(f"CX7 belongs to a {kind} definition in {path}")
                touched = False
                for name, definition in list(ethernets.items()):
                    definition = definition or {}
                    match = definition.get("match", {})
                    ambiguous = (matches_cx7(match, interfaces, by_name) if match else
                                 any(fnmatch.fnmatchcase(n, name) for n in interfaces))
                    ambiguous = (ambiguous or
                                 definition.get("set-name") in interfaces)
                    if name not in interfaces and ambiguous:
                        raise ValueError(f"Ambiguous CX7 match in {path}: {name}; resolve it before setup")
                    if name in interfaces:
                        if match or "set-name" in definition or directory != NETPLAN.parent:
                            raise ValueError(f"Cannot migrate matched/renamed or vendor/runtime CX7 definition in {path}")
                        del ethernets[name]
                        touched = True
                if touched or path == target:
                    changes[path] = yaml.safe_dump(document, sort_keys=False).encode()
            except (yaml.YAMLError, AttributeError, TypeError) as exc:
                raise ValueError(f"Cannot parse Netplan file {path}") from exc
    if (netplan_directories()[2] / target.name).exists():
        raise ValueError(f"/run/netplan/{target.name} would shadow the generated configuration")
    return changes


def preflight(request, info):
    requested_mtu(request)
    journal_path = STATE / "journal.json"
    if journal_path.exists():
        state = json.loads(journal_path.read_text())
        if not request.get("transaction") or state["transaction"] != request["transaction"]:
            raise ValueError("An existing setup journal must be restored before configuring this node again")
    interfaces = request["interfaces"]
    by_name = {item["ifname"]: item for item in info["links"]}
    local_ips = {a["local"] for item in info["links"] for a in item.get("addr_info", [])}
    if local_ips & set(request["nodes"]) != {request["management_ip"]}:
        raise ValueError("Management IP does not uniquely identify this node")
    if not set(interfaces) <= set(sum(PORTS.values(), [])):
        raise ValueError("Only standard Spark CX7 interfaces are supported")
    for name in interfaces:
        if name not in by_name:
            raise ValueError(f"Missing CX7 interface: {name}")
        if "UP" in by_name[name]["flags"] and "LOWER_UP" not in by_name[name]["flags"]:
            raise ValueError(f"CX7 interface has no carrier: {name}")
        if by_name[name].get("master"):
            raise ValueError(f"CX7 interface is enslaved: {name}")
    for item in info["links"]:
        if item["ifname"] in interfaces:
            if any(a["local"] in request["nodes"] for a in item.get("addr_info", [])):
                raise ValueError("A management IP is on a CX7 interface selected for changes")
            continue
        for address in item.get("addr_info", []):
            if address["family"] == "inet":
                existing = ipaddress.ip_interface(f'{address["local"]}/{address["prefixlen"]}').network
                if any(existing.overlaps(ipaddress.ip_network(net)) for net in request["subnets"]):
                    raise ValueError(f"CX7 subnet overlaps existing network on {item['ifname']}; choose --subnet-pool")
    for route in info["routes"]:
        if route.get("dst", "default") == "default" or route.get("dev") in interfaces:
            continue
        existing = ipaddress.ip_network(route["dst"], strict=False)
        if any(existing.overlaps(ipaddress.ip_network(net)) for net in request["subnets"]):
            raise ValueError("CX7 subnet overlaps an existing route; choose --subnet-pool")
    return netplan_changes(interfaces, info["links"], requested_netplan(request))


def render_netplan(interfaces, original=None, *, mtu=DEFAULT_MTU):
    import yaml
    mtu = mtu_value(mtu)
    document = yaml.safe_load(original) if original else {"network": {"version": 2}}
    network = document.setdefault("network", {})
    network.setdefault("version", 2)
    network.setdefault("ethernets", {}).update({
        name: {"dhcp4": False, "dhcp6": False, "link-local": [],
               "mtu": mtu, "addresses": [address]}
        for name, address in interfaces.items()})
    return yaml.safe_dump(document, sort_keys=False).encode()


def network_files(request, changes):
    target = requested_netplan(request)
    return {**changes, target: render_netplan(request["interfaces"], changes.get(target), mtu=requested_mtu(request))}


def validate_netplan(files):
    # Validate the *combined* configuration without touching the live generator.
    with tempfile.TemporaryDirectory(prefix="netplan-check-") as temp:
        root = Path(temp)
        for source, directory in zip(netplan_directories(), ("lib/netplan", "etc/netplan", "run/netplan")):
            target = root / directory
            target.mkdir(parents=True)
            for path in source.glob("*.yaml"):
                shutil.copyfile(path, target / path.name)
                (target / path.name).chmod(0o600)
        for path, data in files.items():
            target = root / "etc/netplan" / path.name
            target.write_bytes(data)
            target.chmod(0o600)
        run(["netplan", "generate", "--root-dir", str(root)])


def ssh_paths(account):
    directory = Path(account.pw_dir) / ".ssh"
    return directory, directory / "spark-vllm-cluster"


def save_routes(interfaces):
    """Keep non-dynamic routes that Netplan may remove from selected NICs.

    iproute2's native stream preserves route attributes and all routing tables.
    Kernel connected routes follow address restoration; DHCP/RA reacquire their
    routes through the restored network configuration.
    """
    saved = []
    for family in ("-4", "-6"):
        routes = json.loads(run(["ip", "-j", family, "route", "show", "table", "all"]).stdout)
        for interface in interfaces:
            protocols = {str(route.get("protocol", "boot")) for route in routes
                         if route.get("dev") == interface and route.get("protocol") not in ("kernel", "dhcp", "ra")}
            for protocol in sorted(protocols):
                data = run(["ip", family, "route", "save", "table", "all", "dev", interface,
                            "proto", protocol], binary=True).stdout
                saved.append({"family": family, "data": base64.b64encode(data).decode()})
    return saved


def remap_route_dump(data, indexes):
    """Translate device references in an iproute2 route-save stream.

    The native-endian stream is a magic word followed by rtnetlink messages
    (iproute2/ip/iproute.c; Linux uapi/linux/rtnetlink.h). Keep every other byte,
    including route metrics, tables, gateways, and message/attribute padding.
    """
    if len(data) < 4 or struct.unpack_from("=I", data)[0] != 0x45311224:
        raise ValueError("Invalid saved route dump header; preserve the journal for recovery")
    output = bytearray(data)

    def remap(offset):
        old = struct.unpack_from("=I", output, offset)[0]
        if not old:  # No interface specified.
            return
        if old not in indexes:
            raise ValueError(f"Saved route references unverified interface index {old}; reconcile routes before restoring")
        struct.pack_into("=I", output, offset, indexes[old])

    def attributes(start, end, *, multipath=True):
        while start < end:
            if end - start < 4:
                raise ValueError("Truncated saved route attribute")
            length, kind = struct.unpack_from("=HH", output, start)
            aligned = (length + 3) & ~3
            if length < 4 or start + aligned > end:
                raise ValueError("Invalid saved route attribute length")
            payload, stop = start + 4, start + length
            if kind in (3, 4):  # RTA_IIF / RTA_OIF
                if length != 8:
                    raise ValueError("Invalid saved route interface reference")
                remap(payload)
            elif kind == 9 and multipath:  # RTA_MULTIPATH: rtnexthop records.
                while payload < stop:
                    if stop - payload < 8:
                        raise ValueError("Truncated saved route nexthop")
                    hop_length = struct.unpack_from("=H", output, payload)[0]
                    if hop_length < 8 or payload + ((hop_length + 3) & ~3) > stop:
                        raise ValueError("Invalid saved route nexthop length")
                    remap(payload + 4)
                    attributes(payload + 8, payload + hop_length, multipath=False)
                    payload += (hop_length + 3) & ~3
            elif kind in (9, 22, 30) or kind > 32:
                # Encapsulation may embed more interface IDs; nexthop objects
                # have separate kernel IDs not captured by the setup journal.
                raise ValueError(f"Saved route attribute {kind} needs manual reconciliation before restore")
            start += aligned

    offset = 4
    while offset < len(output):
        if len(output) - offset < 28:  # nlmsghdr (16) + rtmsg (12).
            raise ValueError("Truncated saved route message")
        length, kind = struct.unpack_from("=IH", output, offset)
        aligned = (length + 3) & ~3
        if length < 28 or offset + aligned > len(output) or kind != 24:  # RTM_NEWROUTE
            raise ValueError("Invalid saved route message")
        if output[offset + 16] not in (2, 10):  # AF_INET / AF_INET6 on Linux.
            raise ValueError("Unsupported saved route address family")
        attributes(offset + 28, offset + length)
        offset += aligned
    return bytes(output)


def restored_routes(journal, links):
    """Validate device identity and build temporary route images, never edit backups."""
    current = {link["ifname"]: link for link in links}
    indexes = {}
    for before in journal.state["runtime"]:
        name = before["ifname"]
        now = current.get(name)
        if now is None:
            raise ValueError(f"Missing saved CX7 interface: {name}; reconcile devices before restoring")
        old_mac, new_mac = before.get("address", "").lower(), now.get("address", "").lower()
        changed = before["ifindex"] != now["ifindex"]
        if (old_mac and old_mac != new_mac) or (changed and not old_mac):
            raise ValueError(f"Cannot verify saved CX7 identity for {name}; reconcile devices before restoring")
        if before["ifindex"] in indexes:
            raise ValueError("Duplicate interface index in saved CX7 inventory")
        indexes[before["ifindex"]] = now["ifindex"]
    result = []
    for routes in journal.state["routes"]:
        if routes["family"] not in ("-4", "-6"):
            raise ValueError("Unsupported saved route family")
        data = base64.b64decode(routes["data"], validate=True)
        result.append((routes["family"], remap_route_dump(data, indexes)))
    return result


def prepare(request, account):
    if (STATE / "journal.json").exists():
        raise ValueError("A setup journal already exists on this node; restore it before a new setup")
    info = inventory(account.pw_name)
    files = network_files(request, preflight(request, info))
    validate_netplan(files)
    directory, managed = ssh_paths(account)
    for path in (directory / "config", directory / "authorized_keys"):
        before = snapshot(path)
        if before and (before["uid"] != account.pw_uid or before["mode"] & 0o022):
            raise ValueError(f"SSH file must be owned by the user and not group/world writable: {path}")
    if managed.exists() or managed.is_symlink():
        raise ValueError(f"Reserved SSH directory already exists: {managed}")
    journal = Journal({"transaction": request["transaction"], "user": account.pw_name,
                       "netplan_file": str(requested_netplan(request)),
                       "files": [], "directories": [], "network_started": False,
                       "interfaces": request["interfaces"], "mtu": requested_mtu(request),
                       "routes": save_routes(request["interfaces"]),
                       "runtime": [item for item in info["links"] if item["ifname"] in request["interfaces"]]})
    journal.save()
    journal.directory(directory, account.pw_uid, account.pw_gid)
    journal.directory(managed, account.pw_uid, account.pw_gid)
    # Generate locally, then journal installation. The private key is never returned.
    with tempfile.TemporaryDirectory(prefix="key-", dir=STATE) as temp:
        key = Path(temp) / "id_ed25519"
        run(["ssh-keygen", "-q", "-t", "ed25519", "-N", "", "-C",
             "spark-vllm:" + request["transaction"], "-f", str(key)])
        for suffix in ("", ".pub"):
            journal.write(managed / ("id_ed25519" + suffix), Path(str(key) + suffix).read_bytes(),
                          uid=account.pw_uid, gid=account.pw_gid)
    return {"public_key": (managed / "id_ed25519.pub").read_text().strip()}


def install_ssh(request, account, journal):
    directory, managed = ssh_paths(account)
    aliases = request["aliases"]
    known = "".join(f"{','.join(item['addresses'])} {key}\n"
                    for item in aliases for key in item["host_keys"])
    journal.write(managed / "known_hosts", known.encode(), uid=account.pw_uid, gid=account.pw_gid)
    auth = directory / "authorized_keys"
    old = auth.read_bytes() if auth.exists() else b""
    addition = "\n".join(request["public_keys"]) + "\n"
    journal.write(auth, old + (b"\n" if old and not old.endswith(b"\n") else b"") + addition.encode(),
                  uid=account.pw_uid, gid=account.pw_gid)
    config = directory / "config"
    old = config.read_bytes() if config.exists() else b""
    hosts = " ".join(address for item in aliases for address in item["addresses"])
    # First-value semantics require this block before existing Host * settings.
    # Reset scope before the user's existing file (which may start with options).
    block = (f"# spark-vllm {request['transaction']}\nHost {hosts}\n"
             f"    User {account.pw_name}\n"
             f'    IdentityFile "{managed}/id_ed25519"\n'
             "    IdentitiesOnly yes\n"
             f'    UserKnownHostsFile "{managed}/known_hosts" ~/.ssh/known_hosts ~/.ssh/known_hosts2\n'
             "    StrictHostKeyChecking yes\nHost *\n")
    journal.write(config, block.encode() + old, uid=account.pw_uid, gid=account.pw_gid)
    return {}


def apply_network(request, journal):
    files = network_files(request, preflight(request, inventory(request["user"])))
    validate_netplan(files)
    for path, data in files.items():
        previous = snapshot(path)
        journal.write(path, data, mode=0o600,
                      uid=previous["uid"] if previous else 0, gid=previous["gid"] if previous else 0)
    journal.state["network_started"] = True
    journal.save()
    run(["netplan", "apply"])
    return {}


def check_restore(journal):
    # Check every path before restoring any of them. Retrying after partial
    # restoration is safe: both the before and after versions are recognized.
    check_docker_restore(journal)
    for entry in journal.state["files"]:
        current = snapshot(Path(entry["path"]))
        if current == entry["before"]:
            continue
        if current and digest(base64.b64decode(current["data"])) == entry["after"] and all(
            current[k] == entry[k] for k in ("mode", "uid", "gid")
        ):
            continue
        raise ValueError(f"Changed since setup: {entry['path']}; preserve/reconcile your edits before restore")
    # Validate every route and device before any file or network changes.
    restored_routes(journal, json.loads(run(["ip", "-j", "link", "show"]).stdout))


def restore_runtime(journal):
    # Netplan can leave addresses/MTUs on now-unmanaged physical interfaces.
    current = {item["ifname"]: item for item in json.loads(run(["ip", "-j", "address", "show"]).stdout)}
    # Recheck after netplan apply in case device enumeration changed again.
    routes_to_restore = restored_routes(journal, current.values())
    for before in journal.state["runtime"]:
        name = before["ifname"]
        original = {f"{a['local']}/{a['prefixlen']}" for a in before.get("addr_info", [])}
        now = {f"{a['local']}/{a['prefixlen']}" for a in current[name].get("addr_info", [])}
        added = journal.state["interfaces"][name]
        if added in now and added not in original:
            run(["ip", "address", "del", added, "dev", name])
        for address in before.get("addr_info", []):
            cidr = f"{address['local']}/{address['prefixlen']}"
            if cidr not in now and not address.get("dynamic"):
                command = ["ip", "address", "replace", cidr, "dev", name]
                if address.get("broadcast"):
                    command += ["broadcast", address["broadcast"]]
                if address.get("scope"):
                    command += ["scope", address["scope"]]
                if address.get("noprefixroute"):
                    command += ["noprefixroute"]
                run(command)
        run(["ip", "link", "set", "dev", name, "mtu", str(before["mtu"]),
             "up" if "UP" in before["flags"] else "down"])
    for family, data in routes_to_restore:
        # iproute2 rewinds stdin between passes: a subprocess input pipe fails
        # with "ftell: Illegal seek". Existing routes are left unchanged.
        with tempfile.TemporaryFile() as stream:
            stream.write(data)
            stream.seek(0)
            run(["ip", family, "route", "restore"], binary=True, stdin=stream)


def restore(journal):
    check_restore(journal)
    # Restore networking first; leave cluster SSH access intact if apply fails.
    for network in (True, False):
        for entry in reversed(journal.state["files"]):
            path = Path(entry["path"])
            if (path.parent == NETPLAN.parent) != network:
                continue
            before = entry["before"]
            if before is None:
                path.unlink(missing_ok=True)
            else:
                atomic_write(path, base64.b64decode(before["data"]), before["mode"], before["uid"], before["gid"])
        if network and journal.state["network_started"]:
            run(["netplan", "apply"])
            restore_runtime(journal)
    restore_docker(journal)
    for path in reversed(journal.state["directories"]):
        try:
            Path(path).rmdir()  # Preserve unrelated files added after setup.
        except OSError:
            pass
    # A hard kill during ssh-keygen can leave its root-only temporary directory.
    for path in STATE.glob("key-*"):
        no_symlinks(path)
        if path.is_dir():
            shutil.rmtree(path)
    (STATE / "journal.json").unlink()
    return {}


def recovery_data(entry, journal, current):
    """Desired contents remain node-local, including private keys and .env."""
    if entry.get("after_data") is not None:
        data = base64.b64decode(entry["after_data"])
        if digest(data) != entry["after"]:
            raise ValueError(f"Recovery image failed its integrity check: {entry['path']}")
        return data
    if current and digest(base64.b64decode(current["data"])) == entry["after"]:
        return base64.b64decode(current["data"])
    # Older journals only stored the after-hash. Reconstruct Netplan from the
    # original local backup, but accept it only if its hash matches exactly.
    path = Path(entry["path"])
    if path.parent == NETPLAN.parent:
        import yaml
        try:
            before = entry["before"]
            document = yaml.safe_load(base64.b64decode(before["data"])) if before else {"network": {"version": 2}}
            ethernets = document.get("network", {}).get("ethernets", {})
            for name in journal.state["interfaces"]:
                ethernets.pop(name, None)
            data = yaml.safe_dump(document, sort_keys=False).encode()
            if path == requested_netplan(journal.state):
                data = render_netplan(journal.state["interfaces"], data, mtu=requested_mtu(journal.state))
            if digest(data) == entry["after"]:
                return data
        except (ValueError, TypeError, AttributeError, yaml.YAMLError):
            pass
    return None


def doctor_report(account, journal):
    if not journal.state["network_started"]:
        raise ValueError("Setup stopped before networking was applied; use --restore before a new setup")
    info = inventory(account.pw_name)
    mtu = requested_mtu(journal.state)
    issues, files, fingerprints = [], [], []
    def issue(message, repairable, kind):
        issues.append({"message": message, "repairable": repairable, "kind": kind})
    for entry in journal.state["files"]:
        path = Path(entry["path"])
        kind = "network" if path.parent == NETPLAN.parent else "file"
        try:
            current = snapshot(path)
            fingerprints.append([str(path), current])
            data = recovery_data(entry, journal, current)
            same_data = current is not None and digest(base64.b64decode(current["data"])) == entry["after"]
            if same_data and all(current[k] == entry[k] for k in ("uid", "gid", "mode")):
                continue
            repairable = data is not None and (current is None or current == entry["before"] or same_data)
            # Known SSH directories can be recreated, but arbitrary missing
            # parent directories need the user's intended location/permissions.
            if not path.parent.exists() and path.parent not in ssh_paths(account):
                repairable = False
            if repairable:
                files.append(str(path))
                issue(f"Restore saved file or permissions: {path}", True, kind)
            else:
                issue(f"Manual reconciliation needed for {path} (edited contents or unavailable recovery image)", False, kind)
        except (ValueError, OSError) as error:
            issue(str(error), False, kind)
    links = {link["ifname"]: link for link in info["links"]}
    network_needed = any(i["kind"] == "network" and i["repairable"] for i in issues)
    for name, cidr in journal.state["interfaces"].items():
        link = links.get(name)
        if not link:
            issue(f"Missing CX7 interface: {name}", False, "network")
            continue
        if link.get("master"):
            issue(f"CX7 interface is enslaved: {name}", False, "network")
        flags = link.get("flags", [])
        if "UP" in flags and "LOWER_UP" not in flags:
            issue(f"No carrier on {name}; check its cable/peer", False, "network")
        addresses = {f"{a['local']}/{a['prefixlen']}" for a in link.get("addr_info", [])}
        subnet = str(ipaddress.ip_interface(cidr).network)
        routed = any(r.get("dev") == name and r.get("dst") == subnet for r in info["routes"])
        if cidr not in addresses or link.get("mtu") != mtu or "UP" not in flags or not routed:
            issue(f"Reapply saved CX7 address, route, MTU {mtu}, and link state: {name}", True, "network")
            network_needed = True
    try:
        membership = docker_preflight(account)
        check_docker_restore(journal)
        if not membership["member"]:
            issue(f"Add {account.pw_name} to the docker group", True, "docker")
        else:
            error = docker_access(account)
            if error:
                issue(error, False, "docker")
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        membership = docker_membership(account)
        issue(str(error), False, "docker")
    return {"interfaces": journal.state["interfaces"], "mtu": mtu, "inventory": info, "issues": issues,
            "repair_files": files, "network_needed": network_needed, "docker": membership,
            "fingerprint": digest(json.dumps([fingerprints, membership], sort_keys=True).encode())}


def repair_node(request, account, journal):
    report = doctor_report(account, journal)
    if report["fingerprint"] != request["fingerprint"]:
        raise ValueError("Configuration changed after doctor inspection; rerun --doctor to review a fresh plan")
    blocked_network = any(i["kind"] == "network" and not i["repairable"] for i in report["issues"])
    paths = set(report["repair_files"])
    if blocked_network:
        paths = {p for p in paths if Path(p).parent != NETPLAN.parent}
    network_files_to_validate = {}
    for entry in journal.state["files"]:
        path = Path(entry["path"])
        if str(path) in paths and path.parent == NETPLAN.parent:
            network_files_to_validate[path] = recovery_data(entry, journal, snapshot(path))
    apply = report["network_needed"] and not blocked_network
    if apply:
        preflight({**request, "netplan_file": str(requested_netplan(journal.state))}, report["inventory"])
        validate_netplan(network_files_to_validate)
    # Preserve before-images from the original setup. Cache matching legacy
    # after-images locally so future doctor runs can recover a deleted file.
    for entry in journal.state["files"]:
        path = Path(entry["path"])
        try:
            data = recovery_data(entry, journal, snapshot(path))
        except (ValueError, OSError):
            continue
        if data is not None and "after_data" not in entry:
            entry["after_data"] = base64.b64encode(data).decode()
            journal.save()
        if str(path) not in paths:
            continue
        for directory in ssh_paths(account):
            if path.is_relative_to(directory) and not directory.exists():
                no_symlinks(directory)
                directory.mkdir(mode=0o700)
                os.chown(directory, account.pw_uid, account.pw_gid)
        atomic_write(path, data, entry["mode"], entry["uid"], entry["gid"])
    if apply:
        run(["netplan", "apply"])
    added = False
    if any(i["kind"] == "docker" and i["repairable"] for i in report["issues"]):
        added = ensure_docker(account, journal)["added"]
    return {"docker_added": added}


def verify(request, account):
    mtu = requested_mtu(request)
    # Diagnose the link before authentication; otherwise a cabling mistake is
    # misleadingly reported as a passwordless SSH failure.
    for interface, address in request["ping_targets"]:
        # IPv4 (20 bytes) + ICMP echo (8 bytes) leaves MTU - 28 for payload.
        result = run(["ping", "-c", "2", "-W", "3", "-M", "do", "-s", str(mtu - 28),
                      "-I", interface, address], check=False)
        if result.returncode:
            raise ValueError(f"CX7 reachability failed: {interface} -> {address}; "
                             f"check cable order, port selection, addresses, and MTU {mtu}")
    for address in request["ssh_targets"]:
        result = run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10",
                      "-o", "ControlMaster=no", "-o", "ControlPath=none",
                      "-o", "PasswordAuthentication=no", "-o", "KbdInteractiveAuthentication=no",
                      address, "true"], user=account.pw_name, check=False)
        if result.returncode:
            # Classify known errors without echoing arbitrary SSH config output.
            reason = next((label for needle, label in (
                ("Permission denied", "authentication rejected"),
                ("Host key verification failed", "host key verification failed"),
                ("REMOTE HOST IDENTIFICATION HAS CHANGED", "host key changed"),
                ("Connection timed out", "connection timed out"),
                ("Connection refused", "connection refused"),
                ("No route to host", "no route to host"),
                ("Network is unreachable", "network is unreachable"),
            ) if needle in result.stderr), f"ssh exited {result.returncode}")
            raise ValueError(f"Passwordless SSH verification failed to {address}: {reason}")
    return {}


def dispatch(request):
    account = pwd.getpwnam(request["user"])
    action = request["action"]
    if action == "inspect":
        return inventory(account.pw_name)
    if action == "preflight-env":
        _, before, _ = env_contents(request, account)
        return {"env_before": env_fingerprint(before)}
    if action == "preflight":
        files = network_files(request, preflight(request, inventory(account.pw_name)))
        validate_netplan(files)
        docker_preflight(account)
        return {"netplan_files": [str(path) for path in files]}
    if action == "verify":
        return verify(request, account)
    if os.geteuid() != 0:
        raise ValueError("Node changes require sudo")
    no_symlinks(STATE)
    readonly = action in ("check-restore", "inspect-setup", "doctor-inspect", "doctor-env")
    if not STATE.exists() and (readonly or action == "restore"):
        if action in ("check-restore", "restore"):
            return {}
        raise ValueError("No saved setup journal on this node; configure the cluster first")
    if not readonly:
        STATE.mkdir(parents=True, mode=0o700, exist_ok=True)
    if STATE.stat().st_uid != 0 or stat.S_IMODE(STATE.stat().st_mode) != 0o700:
        raise ValueError(f"Expected root-owned mode 0700 state directory: {STATE}")
    # Serialize mutating requests and restorations on each node.
    import fcntl
    lock_path = STATE / "lock"
    if readonly and not lock_path.exists():
        lock_path = STATE / "journal.json"
    with lock_path.open("r" if readonly else "a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        if action == "prepare":
            return prepare(request, account)
        path = STATE / "journal.json"
        if not path.exists() and action in ("restore", "check-restore"):
            return {}
        state = json.loads(path.read_text())
        if state["transaction"] != request["transaction"] or state["user"] != account.pw_name:
            raise ValueError("Setup journal belongs to a different transaction/user")
        journal = Journal(state)
        if action == "check-restore":
            check_restore(journal)
            return {}
        if action == "inspect-setup":
            check_restore(journal)
            if not state["network_started"]:
                raise ValueError("Saved setup has not applied networking; finish restoration before retrying")
            return {"interfaces": state["interfaces"], "mtu": requested_mtu(state)}
        if action == "doctor-inspect":
            return doctor_report(account, journal)
        if action == "doctor-repair":
            return repair_node(request, account, journal)
        if action == "restore":
            return restore(journal)
        if action == "ssh":
            return install_ssh(request, account, journal)
        if action == "network":
            return apply_network(request, journal)
        if action == "env":
            return install_env(request, account, journal)
        if action == "doctor-env":
            path, before, contents = env_contents(request, account)
            if any(entry["path"] == str(path) for entry in state["files"]):
                return {"needed": False}  # Covered by the owning node's file report.
            return {"needed": not before or base64.b64decode(before["data"]) != contents or before["mode"] != 0o600}
        if action == "docker":
            return ensure_docker(account, journal)
        raise ValueError("Unknown node action")
